//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_id { get; set; }
        public int task_store_id { get; set; }
        public int task_stremp_id { get; set; }
        public int task_status_id { get; set; }
        public string task_token { get; set; }
        public System.DateTime task_date { get; set; }
        public string task_description { get; set; }
        public string task_moderator_message { get; set; }
        public int task_status_local { get; set; }
        public string task_status_local_message { get; set; }
        public int task_audit_id { get; set; }
        public System.DateTime task_audit_date { get; set; }
        public bool task_audit_deleted { get; set; }
    
        public virtual StatusLocal StatusLocal { get; set; }
        public virtual StatusTask StatusTask { get; set; }
        public virtual Store Store { get; set; }
        public virtual StoreEmployee StoreEmployee { get; set; }
        public virtual User User { get; set; }
    }
}
